### PR TITLE
Temporary fix for 1072 resolution.

### PR DESCRIPTION
**Pull request by Abu3safeer**
This is just temporary until this fixed completely.

### CODE REVIEW

**Comment by simplymemes** [comment]
Curious, what would be considered "fixed completely"?

**Comment by Abu3safeer** [comment]
the m3u8 file contains all resolutions like this:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3067759,RESOLUTION=1280x720,FRAME-RATE=24.000,CODECS="avc1.640028,mp4a.40.2"
https://a-vrv.akamaized.net/evs/xx.mp4/index-v1-a1.m3u8?...
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6308896,RESOLUTION=1920x1072,FRAME-RATE=24.000,CODECS="avc1.640028,mp4a.40.2"
https://a-vrv.akamaized.net/evs/xx.mp4/index-v1-a1.m3u8?...
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1204462,RESOLUTION=854x480,FRAME-RATE=24.000,CODECS="avc1.4d401f,mp4a.40.2"
https://a-vrv.akamaized.net/evs/xx.mp4/index-v1-a1.m3u8?...
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=590507,RESOLUTION=640x360,FRAME-RATE=24.000,CODECS="avc1.4d401e,mp4a.40.2"
https://a-vrv.akamaized.net/evs/xx.mp4/index-v1-a1.m3u8?...
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=434663,RESOLUTION=428x240,FRAME-RATE=24.000,CODECS="avc1.42c015,mp4a.40.2"
https://a-vrv.akamaized.net/evs/xx.mp4/index-v1-a1.m3u8?...
```
As you can see we have:
```
1280x720
1920x1072
854x480
640x360
428x240
```

What I mean by completely is that it should:
1 - fetch all resolutions.
2 - order them by height so it should be like this:
```
1920x1072
1280x720
854x480
640x360
428x240
```
then if the user selected 1080p or best it should look for it, if it didn't it should look for the next lower value which is 1072.

the issue is that it does not look at anything outside this array:
https://github.com/simplymemes/crunchyroll-dl/blob/bc5d7ef94b229cf647078f19b9a591490893ee5c/index.js#L253

this cause it to download 720p.

What I think "completely" means that this app should look for the qualities inside m3u8 file instead of that array, because crunchyroll not necessarily follows those resolutions or aspect ration (like what happend with "GTO the animation")
then instead of comparing it to the array, it should compare it to the m3u8 resolutions.

**Comment by simplymemes** [comment]
I have just pushed 1.3.4 which will rely on the values returned from Crunchyroll rather than the array.

**Comment by Abu3safeer** [comment]
Thank you, I will update it and try it right now.

**Comment by Abu3safeer** [comment]
It works like a charm, now I won't worry about any resolution, even if crunchyroll added 2k or 4k it should be able to handle it.

**Pull request closed without merging**
